spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/investment
    username: sa
    password:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: H2_DB

  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          format_sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  sql:
    init:
      platform: h2
server:
  port: 8080